### ISSUE TITLE
Feature request: allow certain users

### ISSUE THREAD

**Issue by kevinpapst** [xalvarez/prevent-file-change-action#220]
Hi,

I was thinking about using your action to prevent someone from adding changed `*.lock` (eg. from yarn, packages, composer) to PRs. This should prevent that someone sneaks in new packages not updated by the core maintainer.

BUT: when I would now configure your action to fail on `*.lock` I wouldn't be able myself to create new PRs with updated dependencies. Or dependabot for example.

Not sure if your action was made to cover that use-case, but maybe you would consider to add a feature where certain users are allowed to override the pattern?

Not sure about the wording for the new setting I was thinking about, but I imagined something like that:
```
- name: Prevent file change
  uses: xalvarez/prevent-file-change-action@v1
  with:
    githubToken: ${{ secrets.GITHUB_TOKEN }}
    pattern: .*.lock
    maintainer: kevinpapst, xalvarez, dependabot
```
With that setting applied, the 3 users `kevinpapst`, `xalvarez` and `dependabot` would be allowed to pass the pattern rule.

What do you think?

Edit: 

Or is there some other way to achieve the same goal with native Github actions features?

P.S: this is not a bug, the label was added automatically.

**Comment by xalvarez** [comment]
Good idea :+1: I can work on that in the weekend or next week

**Comment by kevinpapst** [comment]
Thanks for the quick and positive response @xalvarez 😄 

In the meantime I tried to use this in my action:

```
    if: ${{ github.actor != 'kevinpapst' && github.actor != 'dependabot[bot]' }}
    steps:
        - name: Prevent file change
          uses: xalvarez/prevent-file-change-action@v1
          with:
            githubToken: ${{ secrets.GITHUB_TOKEN }}
            pattern: .*.lock
```

So only running your action if the user is neither me nor dependabot.

That would achieve the same goal, but:
<img width="974" alt="Bildschirmfoto 2021-12-02 um 14 50 23" src="https://user-images.githubusercontent.com/533162/144434658-66677c43-ec6d-42d9-a584-5da7544d6c16.png">

The `skipped` status will lead to problems when branch protection is activated with `Status checks are required`. There [are workarounds existing](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks), but I believe handling this inside the action is a much cleaner solution.

I can help testing, just give me a ping!
